site_name: CL Documentation
theme:
  name: 'readthedocs'
markdown_extensions:
  - toc:
      permalink: True
nav:
  - index.md
  - Keeping_ontology_terms_up_to_date.md
  - annotation_properties.md
  - presentations.md
  - relations_guide.md
  - resolving_merge_conflicts.md
